package diff

import (
	"testing"
)

// Golden values generated by running npm jsdiff 8.0.4 under node directly.
func TestCreateTwoFilesPatchGolden(t *testing.T) {
	cases := []struct {
		name           string
		oldStr, newStr string
		context        int
		want           string
	}{
		{
			"basic",
			"line1\nline2\nline3\n", "line1\nCHANGED\nline3\nline4\n", 4,
			"--- f\n+++ f\n@@ -1,3 +1,4 @@\n line1\n-line2\n+CHANGED\n line3\n+line4\n",
		},
		{
			"two hunks",
			"a\nb\nc\nd\ne\nf\ng\nh\ni\nj\n", "a\nb\nX\nd\ne\nf\ng\nh\nY\nj\n", 2,
			"--- f\n+++ f\n@@ -1,5 +1,5 @@\n a\n b\n-c\n+X\n d\n e\n@@ -7,4 +7,4 @@\n g\n h\n-i\n+Y\n j\n",
		},
		{
			"no trailing newline",
			"no newline", "still no newline", 3,
			"--- f\n+++ f\n@@ -1,1 +1,1 @@\n-no newline\n\\ No newline at end of file\n+still no newline\n\\ No newline at end of file\n",
		},
		{
			"empty old",
			"", "brand new\n", 4,
			"--- f\n+++ f\n@@ -0,0 +1,1 @@\n+brand new\n",
		},
		{
			"empty new",
			"gone\ngone2\n", "", 4,
			"--- f\n+++ f\n@@ -1,2 +0,0 @@\n-gone\n-gone2\n",
		},
		{
			"identical",
			"same\nsame\n", "same\nsame\n", 4,
			"--- f\n+++ f\n",
		},
		{
			"crlf",
			"a\r\nb\r\n", "a\r\nB\r\n", 4,
			"--- f\n+++ f\n@@ -1,2 +1,2 @@\n a\r\n-b\r\n+B\r\n",
		},
		{
			"context one",
			"one\ntwo\nthree\nfour\nfive\nsix\nseven\n", "one\ntwo\nTHREE\nfour\nfive\nsix\nSEVEN\neight\n", 1,
			"--- f\n+++ f\n@@ -2,3 +2,3 @@\n two\n-three\n+THREE\n four\n@@ -6,2 +6,3 @@\n six\n-seven\n+SEVEN\n+eight\n",
		},
	}
	for _, c := range cases {
		got := CreateTwoFilesPatch("f", "f", c.oldStr, c.newStr, nil, nil,
			&Options{Context: c.context}, &FileHeadersOnly)
		if got != c.want {
			t.Errorf("%s:\n got %q\nwant %q", c.name, got, c.want)
		}
	}
}

type goldenChange struct {
	count          int
	added, removed bool
	value          string
}

func toGolden(changes []Change) []goldenChange {
	out := make([]goldenChange, len(changes))
	for i, c := range changes {
		out[i] = goldenChange{c.Count, c.Added, c.Removed, c.Value}
	}
	return out
}

func equalChanges(a, b []goldenChange) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func TestDiffLinesGolden(t *testing.T) {
	cases := []struct {
		oldStr, newStr string
		want           []goldenChange
	}{
		{"a\nb\n", "a\nc\n", []goldenChange{
			{1, false, false, "a\n"}, {1, false, true, "b\n"}, {1, true, false, "c\n"},
		}},
		{"line1\nline2\nline3\n", "line1\nCHANGED\nline3\nline4\n", []goldenChange{
			{1, false, false, "line1\n"}, {1, false, true, "line2\n"}, {1, true, false, "CHANGED\n"},
			{1, false, false, "line3\n"}, {1, true, false, "line4\n"},
		}},
		{"a\nb\nc\nd\ne\nf\ng\nh\ni\nj\n", "a\nb\nX\nd\ne\nf\ng\nh\nY\nj\n", []goldenChange{
			{2, false, false, "a\nb\n"}, {1, false, true, "c\n"}, {1, true, false, "X\n"},
			{5, false, false, "d\ne\nf\ng\nh\n"}, {1, false, true, "i\n"}, {1, true, false, "Y\n"},
			{1, false, false, "j\n"},
		}},
		{"no newline", "still no newline", []goldenChange{
			{1, false, true, "no newline"}, {1, true, false, "still no newline"},
		}},
		{"", "brand new\n", []goldenChange{{1, true, false, "brand new\n"}}},
		{"gone\ngone2\n", "", []goldenChange{{2, false, true, "gone\ngone2\n"}}},
		{"same\nsame\n", "same\nsame\n", []goldenChange{{2, false, false, "same\nsame\n"}}},
		{"a\r\nb\r\n", "a\r\nB\r\n", []goldenChange{
			{1, false, false, "a\r\n"}, {1, false, true, "b\r\n"}, {1, true, false, "B\r\n"},
		}},
		{"one\ntwo\nthree\nfour\nfive\nsix\nseven\n", "one\ntwo\nTHREE\nfour\nfive\nsix\nSEVEN\neight\n", []goldenChange{
			{2, false, false, "one\ntwo\n"}, {1, false, true, "three\n"}, {1, true, false, "THREE\n"},
			{3, false, false, "four\nfive\nsix\n"}, {1, false, true, "seven\n"},
			{2, true, false, "SEVEN\neight\n"},
		}},
	}
	for _, c := range cases {
		got := toGolden(DiffLines(c.oldStr, c.newStr, nil))
		if !equalChanges(got, c.want) {
			t.Errorf("DiffLines(%q, %q):\n got %+v\nwant %+v", c.oldStr, c.newStr, got, c.want)
		}
	}
}

func TestSplitKeepSeparators(t *testing.T) {
	// Mirrors JS "a\r\nb\nc".split(/(\n|\r\n)/) === ["a", "\r\n", "b", "\n", "c"]
	got := splitKeepSeparators("a\r\nb\nc")
	want := []string{"a", "\r\n", "b", "\n", "c"}
	if len(got) != len(want) {
		t.Fatalf("got %q", got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %q want %q", got, want)
		}
	}
}
