package ignore

import "testing"

// Golden values generated by running npm ignore 7.0.8 under node directly.
func TestIgnoresGolden(t *testing.T) {
	type c struct {
		patterns []string
		paths    []string
		want     []bool
	}
	cases := []c{
		{[]string{"*.log"}, []string{"a.log", "x.logo", "dir/a.log", "a/b/c.log"}, []bool{true, false, true, true}},
		{[]string{"foo/"}, []string{"foo", "foo/", "foo/bar", "a/foo", "a/foo/"}, []bool{false, true, true, false, true}},
		{[]string{"/root"}, []string{"root", "a/root", "root/sub"}, []bool{true, false, true}},
		{[]string{"**/temp"}, []string{"temp", "a/temp", "a/b/temp", "tempx"}, []bool{true, true, true, false}},
		{[]string{"a/**/b"}, []string{"a/b", "a/x/b", "a/x/y/b", "x/a/b"}, []bool{true, true, true, false}},
		{[]string{"a/**"}, []string{"a", "a/x", "a/x/y", "b/x"}, []bool{false, true, true, false}},
		{[]string{"*.log", "!important.log"}, []string{"x.log", "important.log", "a/important.log"}, []bool{true, false, false}},
		{[]string{"dir/", "!dir/file"}, []string{"dir/file", "dir/", "dir/other"}, []bool{true, true, true}},
		{[]string{"#comment", "", "   ", "real"}, []string{"real", "#comment"}, []bool{true, false}},
		{[]string{"a\\ b"}, []string{"a b", "a"}, []bool{true, false}},
		{[]string{"a\\ \\ "}, []string{"a  ", "a ", "a"}, []bool{true, false, false}},
		{[]string{"[a-c].txt"}, []string{"a.txt", "d.txt", "b.txt"}, []bool{true, false, true}},
		{[]string{"[!a].txt"}, []string{"b.txt", "a.txt"}, []bool{true, false}},
		{[]string{"[[:digit:]]x"}, []string{"5x", "ax"}, []bool{true, false}},
		{[]string{"a?c"}, []string{"abc", "ac", "a/c"}, []bool{true, false, false}},
		{[]string{"**/logs/debug.log"}, []string{"logs/debug.log", "a/logs/debug.log", "debug.log"}, []bool{true, true, false}},
		{[]string{"/build/"}, []string{"build/x", "build", "a/build/x"}, []bool{true, false, false}},
		{[]string{"doc/frotz/"}, []string{"doc/frotz", "a/doc/frotz/", "doc/frotz/x"}, []bool{false, false, true}},
		{[]string{"*.LOG"}, []string{"x.log", "X.LOG"}, []bool{true, true}},
		{[]string{"\\#foo"}, []string{"#foo", "foo"}, []bool{true, false}},
		{[]string{"\\!important!.txt"}, []string{"!important!.txt", "important!.txt"}, []bool{true, false}},
		{[]string{"a*"}, []string{"a", "aa", "a/b", "ab/c"}, []bool{true, true, true, true}},
		{[]string{"/*"}, []string{"a", "a/b"}, []bool{true, true}},
		{[]string{"*"}, []string{"a", "a/b"}, []bool{true, true}},
		{[]string{"q?"}, []string{"q", "qa"}, []bool{false, true}},
		{[]string{"[a-]"}, []string{"a", "-", "b"}, []bool{true, true, false}},
		{[]string{"!*.log", "*.tmp"}, []string{"x.log", "y.tmp"}, []bool{false, true}},
		{[]string{"**"}, []string{"a", "a/b", "a/b/c"}, []bool{true, true, true}},
		{[]string{"a/**/"}, []string{"a/x", "a/x/", "a", "a/x/y"}, []bool{false, true, false, true}},
	}
	for _, tc := range cases {
		ig := New(nil)
		ig.Add(tc.patterns...)
		for i, p := range tc.paths {
			var got bool
			func() {
				defer func() {
					if r := recover(); r != nil {
						t.Errorf("panic for %q: %v", p, r)
						got = false
					}
				}()
				got = ig.Ignores(p)
			}()
			if got != tc.want[i] {
				t.Errorf("patterns %v Ignores(%q) = %v, want %v", tc.patterns, p, got, tc.want[i])
			}
		}
	}
}

func TestEmptyPathPanics(t *testing.T) {
	ig := New(nil)
	defer func() {
		if recover() == nil {
			t.Fatal("empty path did not panic")
		}
	}()
	ig.Ignores("")
}

func TestCaseSensitiveOption(t *testing.T) {
	cs := false
	ig := New(&Options{IgnoreCase: &cs})
	ig.Add("*.LOG")
	if ig.Ignores("x.log") {
		t.Fatal("case-insensitive match under IgnoreCase=false")
	}
	if !ig.Ignores("X.LOG") {
		t.Fatal("exact case failed")
	}
}

func TestAddResetsCache(t *testing.T) {
	ig := New(nil)
	ig.Add("*.log")
	if !ig.Ignores("a.log") {
		t.Fatal("pre-negation")
	}
	ig.Add("!a.log")
	if ig.Ignores("a.log") {
		t.Fatal("cache not reset after negation")
	}
}

func TestMultiLinePattern(t *testing.T) {
	ig := New(nil)
	ig.Add("*.log\n*.tmp\r\nx\n")
	for _, p := range []string{"a.log", "b.tmp", "x"} {
		if !ig.Ignores(p) {
			t.Fatalf("%q not ignored", p)
		}
	}
}
